LL-8154 Use BigNumber instead of BigInt
LedgerHQ/ledgerjs pull request #706
Opened 2021-11-17 11:58 UTC by haammar-ledger

https://ledgerhq.atlassian.net/browse/LL-8154

2021-11-17 13:57 UTC, valpinkman approved these changes

2021-11-18 08:17 UTC, gre requested changes
not passing the CI test.

2021-11-18 10:22 UTC, haammar-ledger commented
Dead end, as `BigNumber` doesn't support `bigint` conversion.

2021-11-18 10:22 UTC, closed without merging

2021-11-18 11:24 UTC, gre commented on packages/hw-app-btc/src/newops/psbtv2.ts
> +  b.writeBigUInt64LE(new BigNumber(n), 0);
is this change correct? i'm not sure writeBigUInt64LE will understand new BigNumber 🤔

2021-11-18 11:25 UTC, gre commented on packages/hw-app-btc/src/newops/psbtv2.ts
> +  b.writeBigUInt64LE(new BigNumber(n), 0);
oh sorry wrong pr