Update trc20.js
LedgerHQ/ledgerjs pull request #730
Opened 2021-11-29 14:29 UTC by Alteway

TRC20 token "TEUR" added

2021-12-09 10:41 UTC, haammar-ledger requested changes

2021-12-09 10:41 UTC, haammar-ledger commented on packages/cryptoassets/data/trc20.js
> +  ["TZJmk51TP3YEETw7phRP581A7H3VzLDFsa","TEUR,"EUR AlteWay Token","TZJmk51TP3YEETw7phRP581A7H3VzLDFsa",4]
Missing `"`

2021-12-09 10:49 UTC, Alteway reviewed
Added "

2021-12-09 10:49 UTC, Alteway commented on packages/cryptoassets/data/trc20.js
> +  ["TZJmk51TP3YEETw7phRP581A7H3VzLDFsa","TEUR,"EUR AlteWay Token","TZJmk51TP3YEETw7phRP581A7H3VzLDFsa",4]
Added "

2021-12-11 10:50 UTC, Alteway reviewed
Fixed

2022-01-03 09:49 UTC, gre approved these changes

2022-01-03 09:49 UTC, merged