Stellar: add USDC asset
LedgerHQ/ledgerjs pull request #801
Opened 2022-02-19 01:09 UTC by quietbits

2022-03-07 12:05 UTC, haammar-ledger requested changes

2022-05-02 15:42 UTC, haammar-ledger commented on packages/cryptoassets/src/tokens.ts
> +    // TODO: ??? STELLAR - what is contractAddress used for?
@quietbits Do you want to address that change, so we can merge your work?

2022-05-03 14:17 UTC, quietbits commented on packages/cryptoassets/src/tokens.ts
> +    // TODO: ??? STELLAR - what is contractAddress used for?
@haammar-ledger Would it be OK to merge this together with other related PRs? We might still make changes here (for example, add a home domain). If you prefer to merge as is now and then later make adjustments in a separate PR, I'll remove the comment.

2022-05-30 10:14 UTC, haammar-ledger commented
Included in https://github.com/LedgerHQ/ledger-live/pull/210

2022-05-30 10:14 UTC, closed without merging